title: Sumanth Doddapaneni # your name (or website title) here
logo: "/images/logo1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Class of 2020, ECE
  <br>
  Active researcher in the domains of Natural Language Processing and Computer Vision with a love towards Data Engineering
  <br><br>
  <a href="https://www.linkedin.com/in/sumanth-doddapaneni-25494b130/">Connect with me on LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
