title: Sumanth Doddapaneni # your name (or website title) here
logo: "/images/IMG_6225.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Final Year Undergraduate, ECE
  <br>
  Active researher in the domains of Object Detection, Natural Language Processing with a love towards Data Engineering
  <br><br>
  <a href="https://www.linkedin.com/in/sumanth-doddapaneni-25494b130/">Connect with me on LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
